---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: food2gether
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  frontend
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: busybox:latest # ghcr.io/food2gether/frontend:0.0.1
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "while true; do sleep 600; done"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env: []
        ports:
        - containerPort: 80
          name: frontend
      restartPolicy: Always

