---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: food2gether
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 0
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  frontend
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/kicbase/echo-server:1.0 # ghcr.io/food2gether/frontend:0.0.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env: []
        ports:
        - containerPort: 8080
          name: frontend
      restartPolicy: Always

