---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: food2gether
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  frontend
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/food2gether/frontend:1.2.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
            ephemeral-storage: 1Gi
          limits:
            cpu: 100m
            memory: 100Mi
            ephemeral-storage: 1Gi
        env: []
        ports:
        - containerPort: 8080
          name: frontend
      automountServiceAccountToken: false
      restartPolicy: Always
