---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: frontend
  namespace: food2gether
  labels:
    kubernetes.io/service-name: frontend
addressType: IPv4
ports:
- name: frontend
  appProtocol: http
  protocol: TCP
  port: 8080
endpoints:
- addresses:
  - host.minikube.internal
