name: Publish Docker Image

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

permissions:
  packages: write

jobs:
  publish:
    uses: food2gether/workflows/.github/workflows/frontend-publish.yaml@main
    with:
      version: ${{ github.event.release.tag_name }}
      latest: ${{ !github.event.release.prerelease }}
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}